server:
  port: 8006
spring:
  application:
    name: cloud-payment-consul
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}