server:
  port: 8008
spring:
  application:
    name: cloud-payment-hystrix

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: payment8008
    prefer-ip-address: true  #显示真实的ip地址